// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnwuzjlmiubwormlfffo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRud3V6amxtaXVid29ybWxmZmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTg3OTAsImV4cCI6MjA2ODc3NDc5MH0.lpRyNVcTtBYFF5-_tthOVZi2VBvvfi6amHjXIQcBVoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});